Feature/quan 104
pnarozniak/UniQuanda pull request #12
Opened 2022-10-06 18:34 UTC by Ventan00

Dodano modele bazodanowe odpowiedzialne za header na profilu
Dodato Endpoint zwracający profil
Dodano Redisa
Napisano testy do Handlera

Dodano poprawne z założeniami  zwracanie awatara w responsie Loginu
Zmodyfikowano testy LoginHandlera adekwatnie do zmian z awatarem

2022-10-12 20:37 UTC, Patrykoss requested changes
Prośba o aktualizację modelu Question i przy okazji EfConfiguration. W kontekście komentarzy w EfConfigurations OnDelete, dodałem je w miejscach w których nie było, w celu upewnienia, że jest to zamierzone.

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserInUniversityEfConfiguration.cs
> +            .HasForeignKey(uu => uu.UniversityId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserInUniversityEfConfiguration.cs
> +            .HasForeignKey(uu => uu.AppUserId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserQuestionInteractionEfConfiguration.cs
> +            .HasForeignKey(uq => uq.AppUserId);
#Pytanie Czemu brak OnDelete(DeleteBehavior.Cascade)?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserQuestionInteractionEfConfiguration.cs
> +            .HasForeignKey(uq => uq.QuestionId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserTitleEfConfiguration.cs
> +            .HasForeignKey(ut => ut.AppUserId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserTitleEfConfiguration.cs
> +            .HasForeignKey(ut => ut.AcademicTitleId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/UserPointsInTagEfConfiguration.cs
> +            .HasForeignKey(ut => ut.TagId);
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/UserPointsInTagEfConfiguration.cs
> +        builder.HasOne(ut => ut.AppUserIdNavigation)
#Pytanie Czemu brak OnDelete()?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Core.Domain/Entities/UniversityEntity.cs
> +        public string Logo { get; set; }
#Poprawka Powinno być string?

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +    public async Task<AppUserEntity?> GetUserProfile(int uid, CancellationToken ct)
#Propozycja skrócenia kodu

2022-10-12 20:37 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +    public async Task<AppUserEntity?> GetUserProfile(int uid, CancellationToken ct)
```
    public async Task<AppUserEntity?> GetUserProfile(int uid, CancellationToken ct)
    {
        var cacheKey = "user-profile-statistics";
        var cacheDuration = DurationEnum.THREE_HOURS;

        var user = await _appContext.AppUsers.Where(u => u.Id == uid).Select(u => new AppUserEntity()
        {
            Id = u.Id,
            FirstName = u.FirstName,
            LastName = u.LastName,
            Nickname = u.Nickname,
            Avatar = u.Avatar,
            Banner = u.Banner,
            Titles = _appContext.AppUsersTitles
                    .Include(ut => ut.AcademicTitleIdNavigation)
                    .Where(ut => ut.AppUserId == u.Id)
                    .Select(t => new AcademicTitleEntity()
                    {
                        Id = t.AcademicTitleId,
                        Name = t.AcademicTitleIdNavigation.Name,
                        Type = t.AcademicTitleIdNavigation.AcademicTitleType,
                        Order = t.Order
                    })
                    .ToList(),
            Universities = _appContext.AppUsersInUniversities
                    .Include(uu => uu.UniversityIdNavigation)
                    .Where(uu => uu.AppUserId == uid)
                    .Select(uu => new UniversityEntity()
                    {
                        Id = uu.UniversityId,
                        Name = uu.UniversityIdNavigation.Name,
                        Logo = uu.UniversityIdNavigation.Logo,
                        Order = uu.Order
                    }).ToList(),
            AnswersAmount = _appContext.AppUsersAnswersInteractions.Where(a => a.AppUserId == uid && a.IsCreator).Count(),
            QuestionsAmount = _appContext.AppUsersQuestionsInteractions.Where(q => q.AppUserId == uid && q.IsCreator).Count(),
            Points = _appContext.UsersPointsInTags.Where(p => p.AppUserId == uid).Sum(p => p.Points),
        }).SingleOrDefaultAsync(ct);

        if (user is null)
            return null;

        var cacheResult = await _cacheService.GetFromCache<(int Points, int QuestionAmount, int AnswersAmount)>($"{cacheKey}-{uid}", ct);

        if (object.Equals(cacheResult, default((int Points, int QuestionAmount, int AnswersAmount))))
        {
            (int Points, int QuestionAmount, int AnswersAmount) statistics = (user.Points ?? 0, user.QuestionsAmount ?? 0, user.AnswersAmount ?? 0);
            await _cacheService.SetToCache($"{cacheKey}-{uid}", statistics, cacheDuration, ct);
            return user;
        }
        else
        {
            user.QuestionsAmount = cacheResult.QuestionAmount;
            user.AnswersAmount = cacheResult.AnswersAmount;
            user.Points = cacheResult.Points;
            return user;
        }
    }
```

2022-10-16 15:08 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +    public async Task<AppUserEntity?> GetUserProfile(int uid, CancellationToken ct)
W zaproponowanym rozwiązaniu nie używamy cache w celu przyspieszenia podbierania danych

2022-10-16 15:08 UTC, Ventan00 commented on UniQuanda.Core.Domain/Entities/UniversityEntity.cs
> +        public string Logo { get; set; }
A czy logo uniwersytetu nie jest polem wymaganym? Zakładałem, że uniwersytet przy tworzeniu konta dostarcza nam je. Nie kojarzę uniwersytetu bez logo (ale nie znam wszystkich uniwersytetów). Natomiast według mnie błąd jest w EF Entity University i tam zamiast `string? Logo` powinno być `string Logo`. Co powiecie?

2022-10-16 15:10 UTC, Ventan00 commented
Usunałem nie potrzebne deklaracje relacji oraz tym samym nie ma miejsc gdzie brakuje OnDelete(). Dodatkowo zmieniłem nazwy funkcji w repozytoriach na te z dopiskiem Async

2022-10-16 15:52 UTC, Patrykoss requested changes

2022-10-16 15:52 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            .FirstOrDefaultAsync(ct);
#propozycja Skoro raczej odwołujemy się do faktu, że istnieje tylko taki jeden User, a nie pierwszy z wielu z danego warunku to proponuję użycie SingleOrDefaultAsync()

2022-10-16 15:52 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
#poprawka Jeśli mamy bezpośrednią relację do tabel to proponuję nie odwoływać się do nich poprzez context

2022-10-16 15:52 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
```
user = await query.Select(u => new AppUserEntity()
            {
                Id = u.Id,
                FirstName = u.FirstName,
                LastName = u.LastName,
                Nickname = u.Nickname,
                Avatar = u.Avatar,
                Banner = u.Banner,
                Titles = u.AppUserTitles
                    .Where(ut => ut.AppUserId == u.Id)
                    .Select(t => new AcademicTitleEntity()
                    {
                        Id = t.AcademicTitleId,
                        Name = t.AcademicTitleIdNavigation.Name,
                        Type = t.AcademicTitleIdNavigation.AcademicTitleType,
                        Order = t.Order
                    })
                    .ToList(),
                Universities = u.AppUserInUniversities
                    .Where(uu => uu.AppUserId == uid)
                    .Select(uu => new UniversityEntity()
                    {
                        Id = uu.UniversityId,
                        Name = uu.UniversityIdNavigation.Name,
                        Logo = uu.UniversityIdNavigation.Logo,
                        Order = uu.Order
                    }).ToList(),
                AnswersAmount = u.AppUserAnswersInteractions.Where(a => a.AppUserId == uid && a.IsCreator).Count(),
                QuestionsAmount = u.AppUserQuestionsInteractions.Where(q => q.AppUserId == uid && q.IsCreator).Count(),
                Points = u.UserPointsInTags.Where(p => p.AppUserId == uid).Sum(p => p.Points),
            }).SingleOrDefaultAsync(ct);``
```

2022-10-16 15:52 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
#poprawka Jeśli mamy bezpośrednią relację do tabel to proponuję nie odwoływać się do nich poprzez context

2022-10-16 15:52 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
```
user = await query.Select(u => new AppUserEntity()
            {
                Id = u.Id,
                FirstName = u.FirstName,
                LastName = u.LastName,
                Nickname = u.Nickname,
                Avatar = u.Avatar,
                Banner = u.Banner,
                Titles = u.AppUserTitles
                    .Where(ut => ut.AppUserId == u.Id)
                    .Select(t => new AcademicTitleEntity()
                    {
                        Id = t.AcademicTitleId,
                        Name = t.AcademicTitleIdNavigation.Name,
                        Type = t.AcademicTitleIdNavigation.AcademicTitleType,
                        Order = t.Order
                    })
                    .ToList(),
                Universities = u.AppUserInUniversities
                    .Where(uu => uu.AppUserId == uid)
                    .Select(uu => new UniversityEntity()
                    {
                        Id = uu.UniversityId,
                        Name = uu.UniversityIdNavigation.Name,
                        Logo = uu.UniversityIdNavigation.Logo,
                        Order = uu.Order
                    }).ToList()
            }).SingleAsync(ct);
```

2022-10-16 15:55 UTC, Patrykoss commented on UniQuanda.Core.Domain/Entities/UniversityEntity.cs
> +        public string Logo { get; set; }
Ja chyba sugerowałem się modelem, ale skoro tam jest wymagane pole to tu też powinno zostać string

2022-10-17 00:48 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
Wprowadzam zmiany.
Czy mógłbyś proszę dodatkowo podesłać informacje dlaczego tak powinienem robić?

2022-10-17 15:16 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +            user = await query.Select(u => new AppUserEntity()
Niestety brak artykułu na poparcie, bardziej kwestia doświadczenia z APBD

2022-10-17 15:16 UTC, Patrykoss approved these changes

2022-10-17 15:26 UTC, pnarozniak requested changes
Według mnie powiniśmy zastąpić dostęp do cache poprzez stringa, enumem. Czyli zrobić enuma, podobnie jak DurationEnum z kluczami wskazujacymi na odpowiednie dane np. USER_PROFILE_STATISCS="user-profile-statistics". Oczywście wtedy w cache serwisie wszystkie parametry key:string zastępujemy key:CacheKey

2022-10-17 15:26 UTC, pnarozniak commented
Pozostała część jest dla mnie ok.

2022-10-17 15:58 UTC, pnarozniak approved these changes
k

2022-10-17 15:58 UTC, merged

2022-10-17 16:02 UTC, Patrykoss approved these changes