Feature/quan 109 profile details settings
pnarozniak/UniQuanda pull request #13
Opened 2022-10-06 22:15 UTC by Patrykoss

1. Dodany default User:
- login: user@uniquanda.pl
- hasło: Admin1234
2. Dodana logika aktualizacji danych użytkownika
3.  Wprowadzony podział na foldery w Domain dla Entities na App i Auth ze względu odniesienie kontekstu (propozycja)
4. Przeniesienie Query GetProfile do folderu AppUser (prośba o sprawdzenie podziały na foldery w kontekście Query i Commands)
5. Przeniesie logiki ProfileController do AppUserProfileController

2022-10-18 12:50 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +        // Only for development
#Propozycja
Zmieniłbym to w następujący sposób, by w przyszłości przed deployem w przypadku zapomnienia usunięcia tego, aplikacja nie tworzyła przykładowego użytkownika
```C#
if(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
{
       var users = new List<User>
        {
            new User { Id = 1, Nickname = "Programista", HashedPassword="$2a$12$bIkUNGSkHjgVl80kICadyezV4AgRo6oMwuIEC3X9ian.d7a6xJRIe", RefreshToken=Guid.NewGuid().ToString(), RefreshTokenExp=new DateTime().AddHours(1)} //Password "Admin1234"
        };

        builder.HasData(users);
}
```

2022-10-18 12:54 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEmailEfConfiguration.cs
> +        var userEmails = new List<UserEmail>
#Propozycja
Dodanie `if(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")`

2022-10-18 13:32 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/ImageUploadValidator.cs
> +public class ImageUploadValidator : ValidationAttribute
#Propozycja
Fajnie by było, gdyby do ImageValidatora można było by dodać wymagany rozmiar obrazka (np. 1400 x 200 w przypadku banera). Dodatkowo można by wtedy ustawić default wartości na null i w takim przypadku nie sprawdzać czy wymiary obrazka się zgadzają

2022-10-18 14:02 UTC, Ventan00 commented on UniQuanda.Presentation.API/Controllers/AppUserProfileController.cs
> +    [RequestSizeLimit(21 * 1024 * 1024)]
#Propozycja
Zamiast na sztywno wpisywać wartości proponuję stworzyć enuma w warstwie domain o nazwie ByteSizeEnum.
```C#
namespace UniQuanda.Core.Domain.Enums
{
    public enum ByteSizeEnum
    {
        BYTE = 1,
        KILOBYTE = 1024,
        MEGABYTE = 1024 * 1024,
        GIGABYTE = 1024 * 1024 * 1024,
    }
}
```
i potem wszędzie, gdzie używamy wielkości plików po przez użycie enuma.
```C#
[RequestSizeLimit(21 * (int) ByteSizeEnum.MEGABYTE)]
```
Proponuję to, gdyż uważam że zwiększy to czytelność kodu.

2022-10-18 14:17 UTC, Ventan00 commented on UniQuanda.Infrastructure/Helpers/JwtTokenHelper.cs
> +    public static int? GetAppUserIdFromToken(ClaimsPrincipal claimPrincipal)
#propozycja
Co powiecie by zrobić to jako ExtensionMethod `GetId()` do ClaimsPrincipal?
W tym momencie według mnie będzie czytelniejsze użycie `User.GetId()` niż `JwtTokenHelper.GetAppUserIdFromToken(User)`

2022-10-18 14:50 UTC, pnarozniak commented on UniQuanda.Infrastructure/Helpers/JwtTokenHelper.cs
> +    public static int? GetAppUserIdFromToken(ClaimsPrincipal claimPrincipal)
+1

2022-10-18 15:13 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AppUserRepository.cs
> +        if (!IsDataToUpdate(appUserEntity, appUser))
#poprawka
Proponuję zamiast pisać autorską funkcję do sprawdzania, czy są dane do updateowania użyć następującego kodu:
```C#
        if (appUser is null)
            return new AppUserUpdateResult { IsSuccessful = null };

        appUser.FirstName = appUserEntity.FirstName;
        appUser.LastName = appUserEntity.LastName;
        appUser.City = appUserEntity.City;
        appUser.PhoneNumber = appUserEntity.PhoneNumber;
        appUser.Birthdate = appUserEntity.Birthdate;
        appUser.Avatar = appUserEntity.Avatar;
        appUser.Banner = appUserEntity.Banner;
        appUser.SemanticScholarProfile = appUserEntity.SemanticScholarProfile;
        appUser.AboutText = appUserEntity.AboutText;

       var entity = _appContext.Entry(appUser);
       if ( entity.OriginalValues == entity.CurrentValues )
              return return new AppUserUpdateResult { IsSuccessful = true };
```

2022-10-18 15:16 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileHandler.cs
> +            request.AppUser.Avatar = "AvatarUrl" + Guid.NewGuid().ToString();
#takamyśl
Co powiecie, by po merge tego PR, zająć się S3 - i tak do inżynierki jest konieczny, już byśmy nie musieli mockować

2022-10-18 15:17 UTC, Ventan00 commented on UniQuanda.Core.Application/UniQuanda.Core.Application.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
#pytanie
Gdzie tego używamy?

2022-10-18 15:25 UTC, Ventan00 commented on UniQuanda.Tests/CQRS/Commands/AppUser/Settings/UpdateAppUserProfileHandlerTests.cs
> +        private static ImageUploadResult GetImageUploadResult(bool isSuccessful, string? imageUrl)
#poprawka
Funkcja nigdzie nie używana
Tak samo klasa modelu

2022-10-18 15:26 UTC, Ventan00 requested changes
Proszę o wprowadzenie poprawek i rozważenie wdrożenie propozycji

2022-10-18 15:29 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +            new User { Id = 1, Nickname = "Programista", HashedPassword="$2a$12$bIkUNGSkHjgVl80kICadyezV4AgRo6oMwuIEC3X9ian.d7a6xJRIe", RefreshToken=Guid.NewGuid().ToString(), RefreshTokenExp=new Dat
#poprawka
To w sumie nie zadziała, jak na sztywno haszujesz hasło. Używamy różnych kluczy na różnych środowiskach

2022-10-18 20:12 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +        // Only for development
Wydaje mi się, że w przyszłości i tak stworzymy skrypty SQL, które dodają kilka podstawowych danych do tabel, ale ten moment mogę dodać zmianę

2022-10-18 20:25 UTC, Patrykoss commented on UniQuanda.Presentation.API/Controllers/AppUserProfileController.cs
> +    [RequestSizeLimit(21 * 1024 * 1024)]
Przy okazji tego enuma zmieniam poprzednie wartości enumów na PascalCase zgodnie z opisem z read.me

2022-10-18 20:46 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +            new User { Id = 1, Nickname = "Programista", HashedPassword="$2a$12$bIkUNGSkHjgVl80kICadyezV4AgRo6oMwuIEC3X9ian.d7a6xJRIe", RefreshToken=Guid.NewGuid().ToString(), RefreshTokenExp=new Dat
Jakie aktualny mamy podział na środowiska?

2022-10-18 20:50 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileHandler.cs
> +            request.AppUser.Avatar = "AvatarUrl" + Guid.NewGuid().ToString();
Wydaje mi się, że trzeba trochę z UI nadrobić, ale można to przedyskutować w czwartek

2022-10-18 20:52 UTC, Patrykoss commented on UniQuanda.Core.Application/UniQuanda.Core.Application.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
Potrzebny dla typu plików IFormFile

2022-10-18 20:57 UTC, Patrykoss commented on UniQuanda.Core.Application/Validators/ImageUploadValidator.cs
> +public class ImageUploadValidator : ValidationAttribute
W kontekście rozmiarów obrazu, to nw czy bym go ograniczał przez dokładne rozmiary na ten moment. W przypadku większych rozmiarów aktualnie obraz będzie ucinany, ale wydaje mi się, że w przyszłości będzie można zaimplementować na froncie jakiś mechanizm, który po wybraniu odpowiedniego kadru ucina go np dla Bannera do tego 1400 x 200.

2022-10-18 22:39 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/ImageUploadValidator.cs
> +public class ImageUploadValidator : ValidationAttribute
Tyle, że ucinanie jak rozumiem odbywa się po stronie frontu, ale backend powinien jakoś walidować rozmiar pliku. Tu nie chodzi o mechanizm kadrowania, tylko o mechanizm weryfikacji rozmiaru pliku. Jeśli jest to problematyczne w implementacji, to można chwilowo pominąć. Proszę o odpowiedź / poprawkę

2022-10-18 22:40 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +            new User { Id = 1, Nickname = "Programista", HashedPassword="$2a$12$bIkUNGSkHjgVl80kICadyezV4AgRo6oMwuIEC3X9ian.d7a6xJRIe", RefreshToken=Guid.NewGuid().ToString(), RefreshTokenExp=new Dat
Jeśli dobrze rozumiem pytanie:
* Development (Serwer deweloperski i Localhost)
* Teoretyczny Production (Trzeba stworzyć obraz dockerowy)

Bardziej mi chodziło o to, że hash może być różny przy różnych maszynach - nie wiem dokładnie jak działa bcrypt w tym zakresie, ale wydaje mi się hash na serwerze deweloperskim nie jest tym samym hashem jak podczas developmentu i dlatego bezpieczniej jest hashować serwisem. Jeśli masz większą wiedzę na ten temat, to się proszę podziel.

2022-10-18 22:41 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
>          // Only for development
#propozycja w przypadku jeśli Ci się nudzi (brak konieczności zmiany / odpowiadania)
Jeśli mamy już ifa, to bym usunął komentarz

2022-10-18 22:46 UTC, Ventan00 approved these changes
LGTM

2022-10-20 08:49 UTC, Ventan00 commented
Mam prośbę - w ramach tego PR zrefaktoryzujesz proszę serwis ICacheService, dodając  do suffixu nazw metod `Async`?

2022-10-21 10:40 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileDTO.cs
> +    public string? City { get; set; }
#Poprawka
Zgodnie z wcześniejszymi ustaleniami było 57 znaków dla miasta Taumatawhakatangihangakoauauotamateapokaiwhenuakitanatahu w Nowej Zelandii.
Proszę po poprawkę lub uzasadnienie zmiany.

2022-10-21 10:57 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserEfConfiguration.cs
> +        builder.Property(u => u.AboutText).HasMaxLength(4000).IsRequired(false);
#Poprawka
Zgodnie z wcześniejszymi ustaleniami było 57 znaków dla miasta Taumatawhakatangihangakoauauotamateapokaiwhenuakitanatahu w Nowej Zelandii.
Proszę po poprawkę lub uzasadnienie zmiany.

2022-10-21 11:03 UTC, Ventan00 requested changes
Poproszę o wprowadzenie poprawek, bądź uzasadnienie decyzji

2022-10-21 18:13 UTC, pnarozniak approved these changes
Spoko

2022-10-22 11:05 UTC, Ventan00 approved these changes
LGTM

2022-10-22 11:56 UTC, merged