Dodano integrację do AWS S3
pnarozniak/UniQuanda pull request #14
Opened 2022-10-20 18:44 UTC by Ventan00

Dodano integrację z AWS S3. Secretsy wysłane na messengerze

2022-10-21 18:14 UTC, pnarozniak approved these changes
Wszystko ok, poza użyciem refleksji o ktorym gadaliśmy na uczelni

2022-10-22 23:10 UTC, Patrykoss requested changes

2022-10-22 23:10 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileHandler.cs
> +                var fileName = $"avatar-{request.AppUser.Nickname}";
Wydaje mi się, że nazwa powinna być jednak tworzona na podstawie rzeczy mniej zmiennej jak np IdUsera

2022-10-22 23:10 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileHandler.cs
> +                var fileName = $"banner-{request.AppUser.Nickname}";
Wydaje mi się, że nazwa powinna być jednak tworzona na podstawie rzeczy mniej zmiennej jak np IdUsera

2022-10-22 23:10 UTC, Patrykoss commented on UniQuanda.Core.Application/Services/IImageService.cs
> +        ///     Function to remove image from S3 bucket
remove -> save

2022-10-22 23:10 UTC, Patrykoss commented on UniQuanda.Core.Application/Services/IImageService.cs
> +        ///     Returns image endpoind adress.
#typo endpoint

2022-10-22 23:10 UTC, Patrykoss commented on UniQuanda.Core.Domain/Enums/ImageFolder.cs
> +        public static ImageFolder Root { get { return new ImageFolder(""); } }
#pytanie Co było w tym root trzymane?

2022-10-23 09:04 UTC, Ventan00 commented on UniQuanda.Core.Domain/Enums/ImageFolder.cs
> +        public static ImageFolder Root { get { return new ImageFolder(""); } }
W sumie to nie wiem, tak na prawdę mogę usunąć wszystkie foldery których aktualnie nie używamy (YAGNI)

2022-10-23 09:12 UTC, Patrykoss approved these changes

2022-10-23 09:13 UTC, merged