Feature/QUAN-145 | password recovery
pnarozniak/UniQuanda pull request #15
Opened 2022-10-23 12:23 UTC by pnarozniak

2022-10-23 13:04 UTC, pnarozniak commented
Testy API oraz FRONT będą dodane wkrótce

2022-10-23 16:31 UTC, Patrykoss requested changes
Prośba o załączenie odpowiedzi do pytań

2022-10-23 16:31 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Include(u => u.IdTempUserNavigation)
#propozycja możliwość bez include i wtedy u.IdTempUserNavigation.Id

2022-10-23 16:31 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Include(u => u.IdTempUserNavigation)
#pytanie Czy używamy czegoś z TempUser?

2022-10-23 16:31 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        _authContext.UsersActionsToConfirm.Remove(action);
#pytanie Czemu tutaj najpierw jest attach a później remove tego samego wiersza danych?

2022-10-23 17:15 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        _authContext.UsersActionsToConfirm.Remove(action);
To proponowane przez EF wydajny sposób na usuwanie danych za pomocą PK

2022-10-23 17:17 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Include(u => u.IdTempUserNavigation)
Ten sposób nie zadziała w zamierzony sposób
<img width="855" alt="image" src="https://user-images.githubusercontent.com/53837994/197406004-ad531c8e-019e-4b17-af70-81da4c003cf6.png">

2022-10-23 17:18 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Include(u => u.IdTempUserNavigation)
Tak do sprawdzenia czy user ma potwierdzone konto oraz jak wyżej.

2022-10-23 17:20 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        _authContext.UsersActionsToConfirm.Remove(action);
Dlatego, że nie musimy robić selecta przed deletem.

2022-10-23 17:30 UTC, Patrykoss approved these changes

2022-10-24 16:07 UTC, Patrykoss approved these changes

2022-10-24 16:31 UTC, merged