Feature/quan 110/safety settings
pnarozniak/UniQuanda pull request #18
Opened 2022-10-30 02:12 UTC by Patrykoss

Dodano backend dla strony ustawień bezpieczeństwa użytkownika

2022-11-01 00:28 UTC, pnarozniak commented
Zrobię review API po tym jak zostanie dodana funkcjonalność weryfikacji emaila.

2022-11-15 00:37 UTC, pnarozniak commented on UniQuanda.Presentation.API/Controllers/AuthController.cs
> +        if (result is null)
Propozycja skrócenia zapisu:
`return result is null ? NotFound() : Ok(result)`


W 2 endpointach poniżej analogicznie

2022-11-15 00:46 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/UpdateMainEmail/UpdateMainEmailHandler.cs
> +                    ExistsUntil = DateTime.UtcNow.AddHours(_expirationService.GetNewUserExpirationInHours()),
Proponuje dodać osobny parametr do appsettings dotyczący czasu ważności tokena - gdyż wartości mogą się różnić gdyż są to trochę inne rzeczy.

2022-11-15 00:50 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/ResendConfirmationEmail/ResendConfirmationEmailCommand.cs
> +public class ResendConfirmationEmailCommand : IRequest<bool>
Proponuje zmienić nazwę na ResendEmailChangeConfirmationEmailCommand - gdyż nie wiadomo czego to dotyczy a nie jest to jedyne ponowne wysyłanie e-maila.

2022-11-15 00:54 UTC, pnarozniak commented on UniQuanda.Core.Domain/Enums/AddExtraEmailStatus.cs
> +public enum AddExtraEmailStatus
Dlaczego akurat dla AddExtraEmail wydzieliłeś enum, a już wszystkie pozostałe akcje zgrupowałeś wew. UpdateSecurityResultEnum?

2022-11-15 00:57 UTC, pnarozniak commented on UniQuanda.Core.Application/Services/IEmailService.cs
> +    Task SendInformationAboutUpdateMainEmailAsync(string to, string newMainEmail);
Proponuje nazwać metody w czasie przeszłym jeżeli jest to informacja o dokonaniu czegoś. Na 1 rzut oka nie widać dokładnie i trzeba się upewnić.

2022-11-15 00:58 UTC, pnarozniak commented on UniQuanda.Core.Application/Services/IEmailService.cs
> +    Task SendInformationAboutUpdatePasswordAsync(string to, string nickName);
Ta metoda robi to samo co metoda: SendPasswordHasBeenChangedEmailAsync. Narazie możesz ją zostawić złącze je w przypadku implementacji zadania z template e-maili.

2022-11-15 01:02 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +    public async Task<UserEmailToConfirmValue?> GetUserUnConfirmedEmailAsync(int idUser, CancellationToken ct)
UnConfirmed --> NotConfirmed:

Is it unconfirmed or not confirmed?
Use the adjective unconfirmed to describe something that may or may not be true. If you've heard that there might be a pizza party at school tomorrow, but it hasn't been officially announced, it's just an unconfirmed rumor.

2022-11-15 01:03 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        if (connectedEmail is null)
Propozycja zamiany na return switch

2022-11-15 01:06 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        await using var tran = await _authContext.Database.BeginTransactionAsync(ct);
Wydaje mi się, że customowa transakcja jest tutaj niepotrzebna gdyż w tym przypadku EF sam dobrze tym zarządza. To zwykły UPDATE z możliwością wystąpienia exception kiedy to EF sam cofnie zmiany.

2022-11-15 01:13 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        if (userEmails.Count == 0)
Skoro już mamy return to "ELSE" jest nie potrzebne. Prośba o usunięcie "ELSE" lub zamianę na switcha

2022-11-15 01:15 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +                    await tran.CommitAsync(ct);
Wydaje mi się, że Transakcja tutaj jest niepotrzebna.

2022-11-15 01:16 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            if (await _authContext.SaveChangesAsync(ct) == 2)
Jak wyżej, EF - sam tworzy transakcje na wykonanie się SaveChanges tj. jak np. 1 rzecz się nie usunie to 2 pozostałe też zostaną cofnięte - albo wszystko albo nic.

2022-11-15 01:17 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        if (emailToConfirm is null)
Propozycja użycia ternarnego aby skrócić zapis: 
`return emailToConfirm is null ? null : emailToConfirm.IdUserEmail`
albo w sumie nawet tak o ile tak można w C# bo nie pamietam:
`return emailToConfirm?.IdUserEmail`

2022-11-15 01:19 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/AddExtraEmail/AddExtraEmailHandler.cs
> +            ExistsUntil = DateTime.UtcNow.AddHours(_expirationService.GetNewUserExpirationInHours())
Tak jak wcześniej proponuje stworzenie innej zmiennej niż NewUserExpirationInHours

2022-11-15 01:21 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/ConfirmEmail/ConfirmEmailHandler.cs
> +        if (isSuccess)
Propozycja if(!isSuccess) return false;

Zaleta taka, że nie musimy potem zagnieździć kodu w IFA

2022-11-15 01:22 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/DeleteExtraEmail/DeleteExtraEmailDTO.cs
> +    public int IdExtraEmail { get; set; }
int -> int?  - inaczej nie działa Required (przypisuje się default value - 0). Prośba o upewnienie się, że w pozostałych DTO jest ok, gdyż mogłem przeoczyć

2022-11-15 01:23 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/UpdateMainEmail/UpdateMainEmailHandler.cs
> +    public async Task<UpdateSecurityResultEnum> Handle(UpdateMainEmailCommand request, CancellationToken ct)
Mocno rozrosła się ta funkcja - proponowałbym zrobić tak jak ustaliliśmy kiedyś z Dimą czyli wydzielić kod do 2 prywatnych funkcji tj.  zawartość pierwszego  if (request.IdExtraEmail != null) do 1 a kolejnego do innej. Ciężko się połapać bez tego dla osoby która 1 raz patrzy w ten kod.

2022-11-15 01:24 UTC, pnarozniak requested changes
Prośba o poprawki / odpowiedź na komentarze oraz puszczenie code-cleanupa bo wydaje mi się, że było pare miejsc jakoś inaczej sformatowanych

2022-11-15 01:31 UTC, Patrykoss commented on UniQuanda.Core.Domain/Enums/AddExtraEmailStatus.cs
> +public enum AddExtraEmailStatus
Żeby oddzielić logikę, ponieważ UpdateSecurityResultEnum używam tylko dla commands a ten enum jest dla IsUserAllowedToAddExtraEmailAsync. Ale pomyślę nad lepszą nazwą bo jest to trochę mylące

2022-11-15 01:45 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        if (connectedEmail is null)
Wydaje mi się, że nie da się połączyć tych 3 przypadków

2022-11-16 00:44 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/Auth/ResendConfirmationEmail/ResendConfirmationEmailCommand.cs
> +public class ResendConfirmationEmailCommand : IRequest<bool>
A może ResendEmailWithConfirmationEmailLink albo ResendEmailToConfirmEmailAction?

2022-11-16 00:46 UTC, Patrykoss commented on UniQuanda.Core.Application/Services/IEmailService.cs
> +    Task SendInformationAboutUpdateMainEmailAsync(string to, string newMainEmail);
Nie rozumiem co dokładnie masz na myśli przez czas przeszły

2022-11-16 01:20 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        if (userEmails.Count == 0)
Co masz na myśli poprzez ELSE?

2022-11-16 01:45 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +        await using var tran = await _authContext.Database.BeginTransactionAsync(ct);
Racja. https://learn.microsoft.com/en-us/ef/core/saving/basic -> Multiple Operations in a single SaveChanges

2022-11-16 02:13 UTC, Patrykoss commented
> Prośba o poprawki / odpowiedź na komentarze oraz puszczenie code-cleanupa bo wydaje mi się, że było pare miejsc jakoś inaczej sformatowanych

Zawsze puszczam na całej solucji clean-up. Może kwestia reguł z Mac i Windows jest inna i trzeba je porównać

2022-11-16 23:55 UTC, pnarozniak approved these changes
ok

2022-11-16 23:55 UTC, merged