Feature/quan 155/lista tagów
pnarozniak/UniQuanda pull request #21
Opened 2022-10-31 01:24 UTC by Ventan00

2022-11-03 23:09 UTC, Patrykoss requested changes
Prośba o odpowiedzenie pytań, w celu zrozumienia rozwiązań.

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Presentation.API/Controllers/TagsController.cs
> +            [FromQuery][Required] bool addCount,
#pytanie Czego dotyczy dokładnie addCount?

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +                var mainTag = request.AddParentTagData ?? false && request.TagId != null ? await this._tagRepository.GetTagById(request.TagId ?? 0, ct) : null;
#pytanie Czy mógłbyś wytłumaczyć o co tutaj chodzi? Czym jest main tag? Bo bardzo dużo tutaj logiki się odbywa

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +                    .GetTagsByKeywordAsync(request.PageSize, request.PageSize * (request.Page - 1), request.Keyword, request.TagId, request.OrderDirection, ct)).ToList()
#poprawka Nie potrzeba tutaj robić ToList() według mnie

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +                    }).ToList(),
#poprawka Nie potrzeba tutaj robić ToList() według mnie, ponieważ jest to zwracane jako IEnumerable

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +            else if (request.TagId != null)
#poprawka Jeśli dobrze rozumiem ten if jest odpowiedzialny za pobranie listy subtagów i według mnie powinno to być wydzielone do oddzielnego query

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsDTO.cs
> +        public bool? AddParentTagData { get; set; }
#pytanie Czego dotyczy to pole?

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsDTO.cs
> +        public bool AddCount { get; set; }
#pytanie Czego dotyczy to pole?

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +        builder.Property(t => t.Description).HasMaxLength(500).IsRequired(false);
#Prośba o aktualizację Vertabelo w kontekście dodanych pól.

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +            .HasMethod("GIN");
#pytanie/prośba Czy tu był wybór inna metoda niż "GIN"? Pytam w kontekście opisania tego rozwiązania w dokumentacji inżynierki i ewentualnie jakieś linki (o ile były) i jakieś przemyślenia lub porównania które sobie tworzyłeś. Proponuje to gdzieś spisać bo jesteś na świeżo z tematem.

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +            switch (orderDirection)
#propozycja wydzielenia tego switcha do metody bo jest używana w dwóch miejscach i w przyszłości ułatwi aktualizacje sortowania

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +                    t.SearchVector.Matches(EF.Functions.PlainToTsQuery("polish", keyword))
#prośba Jakbyś mógł wytłumaczyć co tutaj się odbywa?

2022-11-03 23:09 UTC, Patrykoss commented on UniQuanda.Presentation.API/Controllers/TagsController.cs
> +            var query = new GetTagsQuery(dto);
#propozycja połączona z GetTagsHandler, żeby wydzielić koncówkę jedną dla Query GetTags(Główne + keyword) i druga dla subtagów

2022-11-03 23:09 UTC, Patrykoss commented
Migracje w .Net, ścieżki do plików

2022-11-04 10:17 UTC, Ventan00 commented on UniQuanda.Presentation.API/Controllers/TagsController.cs
> +            [FromQuery][Required] bool addCount,
Nie zawsze chcemy pobierać ilość wszystkich tagów które spełniają kryteria filtrowania (np. gdy jest ładowanie 2 strony po wcześniejszym załadowaniu 1 [warunek pobierania ilości tagów tylko przy 1 stronie jest niewystarczający]). AddCount to przełącznik który definiuje czy w responsie należy umieścić ilość wszystkich tagów. Jest to dana potrzebna do obliczenia stron w paginatorze.

2022-11-04 10:22 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +                var mainTag = request.AddParentTagData ?? false && request.TagId != null ? await this._tagRepository.GetTagById(request.TagId ?? 0, ct) : null;
Main Tag, to tag 1 poziomu (nie sub-tag). Przykładowo informatyka, architektura, sztuka, matematyka itp. 

W tym konkretnym przypadku, sprawdzamy, czy aktualnie ładujemy sub-tag i czy mamy do response dołączyć dane main tagu. 

Nie zawsze musimy dołączać dane main-tagu, bo front-end ma dane main-tagu, kiedy przechodzimy do sub-tagu po przez guzik "Pokaż pod-tag".

2022-11-04 10:26 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +            else if (request.TagId != null)
Wydaje mi się, że nie ma sensu robić paru query z takimi samymi parametrami, które w obu przypadkach zwracają ten sam byt (tj. listę tagów), kiedy tak na prawdę sposób pobierania jest podobny a jedyne co się różni, to podanie parentTagId.

2022-11-04 10:27 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsDTO.cs
> +        public bool? AddParentTagData { get; set; }
To pole informuje, czy mamy dołączyć dane main-tagu do response. W przypadku gdy użytkownik wejdzie na pod-tag za pomocą guzika "pokaż pod-tagi" nie ma konieczności dołączania danych main-tagu, gdyż front już je zna. W przypadku wejścia po przez URL na pod-tagi, trzeba dołączyć te dane.

2022-11-04 10:28 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsDTO.cs
> +        public bool AddCount { get; set; }
Odpowiedź taka jak w kontrolerze.

2022-11-04 10:30 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +        builder.Property(t => t.Description).HasMaxLength(500).IsRequired(false);
Pytanie - chcemy trzymać tam też pole które jest generowane i typu TsVector?

2022-11-04 10:36 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +                    t.SearchVector.Matches(EF.Functions.PlainToTsQuery("polish", keyword))
Wyszukiwanie odbywa się za pomocą 2 składników.
1. ILike z tytułem tagu
2. Użyciem autogenerowanej kolumny z nazwy tagu i jego opisu o nazwie SearchVector. Kolumna ta zawiera podstawowe wersje słów (np. z  słowa "Informatyki" robi słowo "Informatyka"). Wyszukiwanie odbywa się po przez sprowadzenie wprowadzonej wartości do jej podstawowej formy i sprawdzenie, czy takie słowo występuje w tej generowanej kolumnie. 

Jeśli któryś z warunków jest spełniony, to zwracamy ten tag.

2022-11-04 10:43 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +            .HasMethod("GIN");
Tak, był jeszcze index GIST.
Korzystałem z tego tutoriala https://www.npgsql.org/efcore/mapping/full-text-search.html?tabs=pg12%2Cv5\

Nie robiłem porównań bo wyszedłem z założenia - działa fulltext search - nice, ale jeśli uważasz, że trzeba zrobić porównanie gist i gin w tym przypadku, to mogę to opisać i tu i w inżynierce (pytanie gdzie w inżynierce)

2022-11-04 10:46 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +            .HasMethod("GIN");
bazując w sumie na tym 
https://www.postgresql.org/docs/9.1/textsearch-indexes.html
zostawiłbym GIN, gdyż jest to rzadko przebuildowywany index, szybszy w wyszukiwaniu (a najczęściej będziemy wyszukiwać) i przy tagach nie istotne jest dla nas ile miejsca zajmuje, gdyż tagów będzie do 1000 (na oko)

2022-11-04 10:48 UTC, Ventan00 commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +            else if (request.TagId != null)
Też w sumie myślę, wtedy trzeba będzie przenieść tę logikę do frontendu

2022-11-04 18:07 UTC, Patrykoss commented
Podział w handlerze na 3 prywatne funkcje

2022-11-08 22:53 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +            switch (orderDirection)
Zrobiłem extension method która przyjmuje enuma - powoduje to reużywalność między repozytoriami

2022-11-08 23:00 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Tags/GetTags/GetTagsHandler.cs
> +                var mainTag = request.AddParentTagData ?? false && request.TagId != null ? await this._tagRepository.GetTagById(request.TagId ?? 0, ct) : null;
To tylko prośba o zmianę na parentTag

2022-11-08 23:02 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/TagEfConfiguration.cs
> +        builder.Property(t => t.Description).HasMaxLength(500).IsRequired(false);
Jeśli dobrze zapamiętałem z ustaleń z uczelni to chcemy to mieć, więc prośba o aktualizację w Vertabelo

2022-11-17 00:12 UTC, Patrykoss requested changes
Plus poprawka migracji

2022-11-17 00:12 UTC, Patrykoss commented on UniQuanda.Core.Application/Repositories/ITagRepository.cs
> +        public Task<TagEntity> GetTagById(int tagId, CancellationToken ct);
#poprawka brak async w nazwie

2022-11-17 00:12 UTC, Patrykoss commented on UniQuanda.Presentation.API/Filters/EnumSchemaFilter.cs
> +        public void Apply(OpenApiSchema model, SchemaFilterContext context)
#pytanie Do czego służy ta metoda?

2022-11-17 13:06 UTC, Ventan00 commented on UniQuanda.Presentation.API/Filters/EnumSchemaFilter.cs
> +        public void Apply(OpenApiSchema model, SchemaFilterContext context)
Do tego, by w swaggerze w polach, gdzie argumentem jest enum, nie była lista integerów tylko "integer - nazwa enuma" (np. 0 - Ascending)

2022-11-20 13:23 UTC, Ventan00 commented on UniQuanda.Presentation.API/Filters/EnumSchemaFilter.cs
> +        public void Apply(OpenApiSchema model, SchemaFilterContext context)
Okazuje się, że zmiana powodowała, że swagger jest nieużyteczny. Szybciej było wywalić niż naprawiać

2022-11-20 14:08 UTC, Patrykoss requested changes

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/Models/University.cs
> +    public University() { }
#pytanie Czy ten konstruktor jest potrzebny?

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/Models/Tag.cs
> +    public Tag() { }
#pytanie Czy ten konstruktor jest potrzebny?

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/Models/AcademicTitle.cs
> +    public AcademicTitle() { }
#pytanie Czy ten konstruktor jest potrzebny?

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +        public async Task<int> GetParentTagsCountAsync(CancellationToken ct)
#propozycja dla podkreślenie funkcjonalności GetAmountOfParentTagsAsync

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +        public async Task<int> GetSubTagsCountAsync(int tagId, CancellationToken ct)
#propozycja dla podkreślenie funkcjonalności GetAmountOfSubTagsAsync

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +        public async Task<int> GetTagsByKeywordCountAsync(string keyword, CancellationToken ct)
#propozycja dla podkreślenie funkcjonalności GetAmountOfTagsByKeywordAsync

2022-11-20 14:08 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/TagRepository.cs
> +        public async Task<int> GetSubTagsByKeywordCountAsync(string keyword, int tagId, CancellationToken ct)
#propozycja dla podkreślenie funkcjonalności GetAmountOfSubTagsByKeywordAsync

2022-11-20 14:22 UTC, Patrykoss approved these changes

2022-11-20 14:23 UTC, merged