feature/QUAN-158 | report-system
pnarozniak/UniQuanda pull request #22
Opened 2022-11-04 21:15 UTC by pnarozniak

2022-11-04 21:53 UTC, pnarozniak commented
Front będzie wrzucony w ciągu kilku h

2022-11-06 20:31 UTC, Patrykoss requested changes

2022-11-06 20:31 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/Models/Report.cs
> +		public Report()
#pytanie Czy jest ten konstruktor potrzebny?

2022-11-06 20:31 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/Migrations/20221104225703_ReportTypeInitialDataSeed.cs
> +                    { 3, "Nękanie lub cybeprzemoc", ReportCategoryEnum.USER },
#typo cyberprzemoc

2022-11-06 20:31 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/Report/CreateReport/CreateReportDTO.cs
> +		public int? ReportedEntityId { get; set; }
Skoro required to czemu int?

2022-11-06 20:31 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/ReportRepository.cs
> +			.SingleOrDefaultAsync();
Not added CancelationToken

2022-11-06 22:09 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Report/CreateReport/CreateReportDTO.cs
> +		public int? ReportedEntityId { get; set; }
https://stackoverflow.com/questions/6662976/required-attribute-for-an-integer-value

2022-11-06 22:12 UTC, pnarozniak commented on UniQuanda.Infrastructure.Presistence/AppDb/Models/Report.cs
> +		public Report()
Usunę

2022-11-07 21:09 UTC, Patrykoss approved these changes

2022-11-08 00:40 UTC, merged