Bug fix/quan 157/update user profile
pnarozniak/UniQuanda pull request #25
Opened 2022-11-21 15:51 UTC by Patrykoss

- Naprawa błędu spowodowanego nadpinsaniem aktualna avatar lub bannera nullem
- Dodanie ResponseDTO dla sekcji security

2022-11-28 00:09 UTC, pnarozniak requested changes
Prośba o odpowiedz na pytania

2022-11-28 00:09 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileDTO.cs
> +    public bool IsNewAvatar { get; set; }
Czy tutaj nie trzeba dać bool? tak jak przy int ?

2022-11-28 00:09 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileDTO.cs
> +    public bool IsNewBanner { get; set; }
Czy tutaj nie trzeba dać bool? tak jak przy int ?

2022-11-28 01:18 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileDTO.cs
> +    public bool IsNewAvatar { get; set; }
Tak, trzeba było zrobić bool?

2022-11-28 01:18 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/AppUser/Profile/UpdateAppUserProfile/UpdateAppUserProfileDTO.cs
> +    public bool IsNewBanner { get; set; }
Tak, trzeba było zrobić bool?

2022-12-01 17:26 UTC, pnarozniak approved these changes
ok

2022-12-01 22:02 UTC, merged