Feature/quan 86
pnarozniak/UniQuanda pull request #3
Opened 2022-06-14 17:48 UTC by Ventan00

Ustawiłem ścieżkę pakietów NuGet relatywną względem projektu, w celu poprawnego ładowania aplikacji na dockerze i możliwości pracy nad nią w Visual Studio bez wyświetlania się błędów o nie udanych importach.

2022-06-14 19:23 UTC, Patrykoss requested changes

2022-06-14 19:23 UTC, Patrykoss commented on UniQuanda.Tests/UnitTest1.cs
> +using NUnit.Framework;
Please, remove unused class of tests.

2022-06-14 19:24 UTC, Patrykoss requested changes

2022-06-14 19:24 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/Class1.cs
> +﻿namespace UniQuanda.Infrastructure.Presistence
Please, remove unused class

2022-06-14 21:58 UTC, Ventan00 commented on UniQuanda.Tests/UnitTest1.cs
> +using NUnit.Framework;
Usunięto

2022-06-14 21:58 UTC, Ventan00 commented on UniQuanda.Infrastructure.Presistence/Class1.cs
> +﻿namespace UniQuanda.Infrastructure.Presistence
Usunięto

2022-06-15 09:13 UTC, Patrykoss approved these changes

2022-06-16 13:33 UTC, pnarozniak approved these changes
ok

2022-06-16 13:36 UTC, merged