Feature/QUAN-85
pnarozniak/UniQuanda pull request #4
Opened 2022-06-22 00:03 UTC by pnarozniak

2022-06-22 18:06 UTC, Ventan00 commented on UniQuanda.Presentation.API/Controllers/AuthController.cs
> +        [ProducesResponseType(StatusCodes.Status409Conflict)]
Nie zgodne ze zwracaną wartością

2022-06-22 19:47 UTC, Patrykoss requested changes

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/Auth/Register/RegisterDTO.cs
> +        [MinLength(6)]
I think it should be removed or change for MinLength(2)

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Queries/Auth/IsEmailAndNicknameAvailable/IsEmailAndNicknameAvailableDTO.cs
> +        [MinLength(6)]
I think it should be removed or change for MinLength(2)

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/Models/User.cs
> +        public virtual ICollection<UserEmail> Emails { get; set; }
I would go with higher abstractions IEnumerable

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Application/Repositories/IAuthRepository.cs.cs
> +        /// Checks if given e-mail is currently being used by any user
Unnecessary word being

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Application/Repositories/IAuthRepository.cs.cs
> +        /// Checks if given nickname is currently being used by any user
Unnecessary word being

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Application/Repositories/IAuthRepository.cs.cs
> +        /// <param name="email">Email by which user will be search</param>
searched

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Core.Domain/ValueObjects/UserEmail.cs
> +        public int Id { get; set; }
I would remove, because it is never used

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +                .Where(u => EF.Functions.ILike(u.Emails.Select(ue => ue.Value).First(), email))
If it will work I would join conditions to only one where

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Presentation.API/Controllers/AuthController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(LoginResponseDTO))]
For better visibility, i would change code order, to first be 200Ok

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Presentation.API/Controllers/AuthController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
For that endpoint when it is failed, i would say that it is BadRequest, because, it mostly based that data given by client is incorrect

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +namespace UniQuanda.Infrastructure.Services.Auth
I would consider using argon2 over bcrypt based on comments and articles from net

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +                .Where(tu => EF.Functions.ILike(tu.IdUserNavigation.Emails.Select(e => e.Value).First(), email))
I would exchange condition, to be sure that is it 100% main email
.Where(tu => EF.Functions.ILike(tu.IdUserNavigation.Emails.SingleOrDefault(e => e.IsMain == true).Value, email))

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AppDb/EfConfigurations/AppUserEfConfiguration.cs
> +    public class AppUserEfConfiguration : IEntityTypeConfiguration<AppUser>
Set singular name of table

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/TempUserEfConfiguration.cs
> +    public class TempUserEfConfiguration : IEntityTypeConfiguration<TempUser>
Set singular name of table

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEfConfiguration.cs
> +    public class UserEfConfiguration : IEntityTypeConfiguration<User>
Set singular name of table

2022-06-22 19:47 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/EfConfigurations/UserEmailEfConfiguration.cs
> +    public class UserEmailEfConfiguration : IEntityTypeConfiguration<UserEmail>
Set singular name of table

2022-06-22 21:45 UTC, Patrykoss commented
If you didn't make clean code from VS, please do it

2022-06-22 22:32 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Commands/Auth/Register/RegisterDTO.cs
> +        [MinLength(6)]
I can't agree 6chars is minimum for username for me.

2022-06-22 22:32 UTC, pnarozniak commented on UniQuanda.Core.Application/CQRS/Queries/Auth/IsEmailAndNicknameAvailable/IsEmailAndNicknameAvailableDTO.cs
> +        [MinLength(6)]
I can't agree 6chars is minimum for username for me.

2022-06-22 22:33 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +                .Where(tu => EF.Functions.ILike(tu.IdUserNavigation.Emails.Select(e => e.Value).First(), email))
There is not other opiton. Temp user have only main email.

2022-06-22 22:38 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +                .Where(u => EF.Functions.ILike(u.Emails.Select(ue => ue.Value).First(), email))
I think it is way more readable if conditions are separated.

2022-06-22 22:40 UTC, pnarozniak commented on UniQuanda.Presentation.API/Controllers/AuthController.cs
> +        [ProducesResponseType(StatusCodes.Status204NoContent)]
I can't agree. 400 means that the request could not be understood by the server due to malformed syntax.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

2022-06-22 22:41 UTC, pnarozniak commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +namespace UniQuanda.Infrastructure.Services.Auth
Please attach some kind of link to the resources about it.

2022-06-22 22:43 UTC, pnarozniak commented on UniQuanda.Infrastructure.Presistence/AuthDb/Models/User.cs
> +        public virtual ICollection<UserEmail> Emails { get; set; }
https://stackoverflow.com/questions/10113244/why-use-icollection-and-not-ienumerable-or-listt-on-many-many-one-many-relatio

2022-06-22 22:47 UTC, pnarozniak commented
I can't agree to all your change requests. We can discuss them on sprint review.

2022-06-23 10:58 UTC, Patrykoss commented on UniQuanda.Infrastructure.Presistence/AuthDb/Models/User.cs
> +        public virtual ICollection<UserEmail> Emails { get; set; }
Ok, we can stay with that

2022-06-23 14:16 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/PasswordValidator.cs
> +            var pattern = "^.*[A-Z]+[a-z]+[0-9]+.*";
Do zmiany

2022-06-30 10:12 UTC, Ventan00 commented on UniQuanda.Presentation.API/Program.cs
>  app.UseHttpsRedirection();
Dodaj warunek app.Enviroment.IsProduction() (lub !IsEnviroment()) by w wersji produkcyjnej poprawnie CORS działał

2022-06-30 11:58 UTC, Ventan00 commented
Usunąć klasy Questions które służyły do testów

2022-06-30 12:07 UTC, Patrykoss approved these changes

2022-06-30 13:00 UTC, Ventan00 commented on UniQuanda.Infrastructure/Services/SendGridService.cs
> +        var emailMessage = $"<span>Your code is: <b>{confirmationToken}</b></span>";
Co myślicie o ładowaniu z pliku od razu?

2022-06-30 13:18 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/DateTimeEarlierThanCurrentValidator.cs
> +        var date = Convert.ToDateTime(value);
try catch dla FormatException oraz InvalidCastException

2022-06-30 13:20 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/PasswordValidator.cs
> +        var password = (string)value;
try catch dla InvalidCastException

2022-06-30 13:26 UTC, Ventan00 commented on UniQuanda.Core.Domain/Entities/NewUserEntity.cs
> +    public DateTime ExistsTo { get; set; }
ExistsUntil

2022-06-30 13:50 UTC, Ventan00 commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +        return BCrypt.Net.BCrypt.HashPassword(plainPassword);
Trzeba podjąć decyzję Argon2 vs BCrypt. Jak to rozwiążemy?

2022-06-30 13:55 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .AnyAsync(u => u.Emails.Any(ue => EF.Functions.ILike(ue.Value, email)));
Jaki jest powód dania ILike zamiast ue.Value == email

2022-06-30 13:55 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .AnyAsync(u => EF.Functions.ILike(u.Nickname, nickname));
Jaki jest powód danie ILike zamiast u.Nickname == Nickname

2022-06-30 14:04 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            return await _authContext.SaveChangesAsync() >= 3;
Kiedy może być sytuacja że wartość będzie != 3. Czy testowałeś co się stanie jeśli np. Email lub nick już jest zajęty? Czy wtedy zwraca exceptiona i/albo dodaje nie pełne dane?

2022-06-30 14:05 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Where(u => u.Emails.Any(ue => EF.Functions.ILike(ue.Value, email)))
Jaki jest cel użycia ILike?

2022-06-30 14:06 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Where(u => EF.Functions.Like(u.IdTempUserNavigation.EmailConfirmationCode, confirmationCode))
Po co ilike?

2022-06-30 14:10 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .Where(tu => EF.Functions.ILike(tu.IdUserNavigation.Emails.Select(e => e.Value).First(), email))
Po co ilike?

2022-06-30 14:11 UTC, Ventan00 requested changes
Co robimy z CancelationToken w Query. Ja jestem za dodaniem

2022-06-30 18:24 UTC, pnarozniak commented on UniQuanda.Infrastructure/Services/SendGridService.cs
> +        var emailMessage = $"<span>Your code is: <b>{confirmationToken}</b></span>";
Trzeba podjąć decyzję, czy chcemy ręcznie to obsługiwać czy skorzystać z gotowego mechanizmu oferowanego przez SendGrid (dynamic-templates)

2022-06-30 18:25 UTC, pnarozniak commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +        return BCrypt.Net.BCrypt.HashPassword(plainPassword);
Ktoś musi zrobić research i przedstawić zalety i wady obydwu. Innej opcji raczej nie ma - dlatego proponuje pominąć to w tym taksu / dodać issue na jirrze

2022-06-30 18:26 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .AnyAsync(u => u.Emails.Any(ue => EF.Functions.ILike(ue.Value, email)));
Korzystam z wbudowanych funkcji LIKE / ILIKE ze względu na wydajność zapytań, a dodatkowo == jest to sprawdzenie case-sensitive.

Ta sama odpowiedź do wszystkich poniższych uwag.

2022-06-30 18:28 UTC, pnarozniak commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            return await _authContext.SaveChangesAsync() >= 3;
W takim przypadku zostaje rzucony exception. dlatego całość wzięta jest w try catch. Teoretycznie nie może być sytuacji żeby saveChangesAsync było != 3 ale ze względu na czytelność kodu uznałem, że warto to zaznaczyć.

Wszystkie tego typu działania w EF objęte są jako transakcja, więc nie ma możliwości aby dane zostały wstawione częściowo (ps. testowałem).

2022-06-30 18:35 UTC, pnarozniak commented on UniQuanda.Core.Application/Validators/PasswordValidator.cs
> +        var password = (string)value;
Wydaje mi się, że nie istnieje opcją aby ta operacja rzuciła exception. Jeżeli jest napisz prosze kiedy.

2022-06-30 18:37 UTC, pnarozniak commented on UniQuanda.Core.Application/Validators/DateTimeEarlierThanCurrentValidator.cs
> +        var date = Convert.ToDateTime(value);
Dając tą anotację nad jakiekolwiek pole typu DateTime powoduje, że nie możliwym jest aby ty wyjątki zostały rzucone.

Wyjątek może być wyłacznie w sytaucji gdy ktoś np. da przez nieuwagę tą anotacje na pole typu int / string itd....

2022-07-01 08:54 UTC, Ventan00 commented on UniQuanda.Infrastructure/Services/SendGridService.cs
> +        var emailMessage = $"<span>Your code is: <b>{confirmationToken}</b></span>";
W takim razie teraz może tak zostać i trzeba uzgodnić na weekly jak to robimy

2022-07-01 09:01 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/DateTimeEarlierThanCurrentValidator.cs
> +        var date = Convert.ToDateTime(value);
No i dla tego myślałem, by nawet w takiej sytuacji anotacja nie rzucała exceptionem, tylko po prostu zwracała wartość false.

2022-07-01 09:01 UTC, Ventan00 commented on UniQuanda.Core.Application/Validators/PasswordValidator.cs
> +        var password = (string)value;
W momencie gdy damy klasę która nie implementuje [IConvertible](https://docs.microsoft.com/pl-pl/dotnet/api/system.iconvertible?view=net-6.0). Tak jak w powyższym przypadku (z date validatorem) wydaje mi się, że lepiej nie rzucać exceptiona, tylko zwrócić informację, że podany walidator jest nie poprawny

2022-07-01 09:01 UTC, Ventan00 commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +        return BCrypt.Net.BCrypt.HashPassword(plainPassword);
Ok, możemy tak zrobić

2022-07-01 09:05 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            return await _authContext.SaveChangesAsync() >= 3;
No to jeśli testowałeś i to tak działa, to git. Skoro nie ma takiej sytuacji, by SaveChangesAsync było != 3, to zmień warunek na == 3 bo nie widzę zysku czytelności, a bez tego, warunek jest nie ściśle poprawny.

2022-08-01 17:46 UTC, Patrykoss requested changes

2022-08-01 17:46 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/Auth/Login/LoginHandler.cs
> +        await _authRepository.UpdateUserRefreshTokenAsync(appUser.Id, refreshToken, refreshTokenExp);
Shouldn't be handled response? From docs of IAuthRepository:
 <returns>True if refresh token was updated, NULL if user was not found, otherwise False</returns>

2022-08-01 17:46 UTC, Patrykoss commented on UniQuanda.Core.Application/CQRS/Commands/Auth/ResendRegisterConfirmationCode/ResendRegisterConfirmationCodeHandler.cs
> +        if (isUpdated is null or false) return false;
I would go with return for new line

2022-08-04 16:36 UTC, Ventan00 commented on UniQuanda.Infrastructure/Services/Auth/PasswordsService.cs
> +        return BCrypt.Net.BCrypt.HashPassword(plainPassword);
Zostawiamy BCrypta

2022-08-04 16:41 UTC, Ventan00 commented on UniQuanda.Infrastructure/Repositories/AuthRepository.cs
> +            .AnyAsync(u => u.Emails.Any(ue => EF.Functions.ILike(ue.Value, email)));
zostawiamy ILIKE po rozmowie

2022-08-04 16:44 UTC, Ventan00 commented
robimy cancelationToken w Query

2022-08-06 22:31 UTC, pnarozniak commented
Okazuje się ze cancelationToken już jest i w Query i w Command

2022-08-07 12:07 UTC, Ventan00 requested changes
Cancelation token powinien być przyjmowany w funkcji kontrolera np.
```C#
public async Task<IActionResult> Register([FromBody] RegisterRequestDTO request, CancellationToken token)
```
i przekazywany do mediatora w funkcji send
```C#
var isRegistered = await _mediator.Send(command,token);
```
Następnie w handlerze w funkcji
```C#
public async Task<bool> Handle(ConfirmRegisterCommand request, CancellationToken cancellationToken)
```
powinien być przekazywany do repozytorium
```C#
return await _authRepository.ConfirmUserRegistrationAsync(request.Email, request.ConfirmationCode, cancellationToken);
```
Repozytorium powinno przyjmować ten token i używać go w funkcjach ToListAsync(), AnyAsync() itp.

2022-08-07 15:58 UTC, Ventan00 commented on UniQuanda.Presentation.API/appsettings.json
> +    "Url": "https://localhost:4200"
Prośba o zmianę na http

2022-08-16 16:17 UTC, Ventan00 approved these changes
Ok

2022-08-16 17:04 UTC, merged